# Generated by doctest: do not edit by hand
# Please edit file in R/palindrome.R

test_that("Doctest: palindrome", {
  # Created from @doctest for `palindrome`
  # Source file: R/palindrome.R
  # Source line: 9
  p <- palindrome()
  expect_match(p, "Panama")
  pal_letters <- unlist(strsplit((function(x) gsub("[^A-z]", "", x))(tolower(p)),
  ""))
  expect_equal(pal_letters, rev(pal_letters))
})

