# Generated by doctest: do not edit by hand
# Please edit file in R/safe-arithmetic.R

test_that("Doctest: safe_mean", {
  # Created from @doctest for `safe_mean`
  # Source file: R/safe-arithmetic.R
  x <- 1:3
  expect_equal(safe_mean(x), 2)
})

test_that("safe-mean-errors", {
  # Created from @doctest for `safe_mean`
  # Source file: R/safe-arithmetic.R
  expect_warning(safe_mean("a"), "not numeric")
  expect_warning(safe_mean(c(1, NA)), "NA elements")
})

