# Generated by doctest: do not edit by hand
# Please edit file in R/safe-arithmetic.R

test_that("Doctest: add", {
  # Created from @doctest for `add`
  # Source file: R/safe-arithmetic.R
  # Source line: 56
  expect_equal(1 + 1, add(1, 1))
})

