# Generated by doctest: do not edit by hand
# Please edit file in R/safe-arithmetic.R

test_that("Doctest: %plus%", {
  # Created from @doctest for `%plus%`
  # Source file: R/safe-arithmetic.R
  # Source line: 73
  expect_equal(2 %plus% 2, 4)
})

