# Generated by doctest: do not edit by hand
# Please edit file in R/safe-arithmetic.R

test_that("Doctest: safe_var", {
  # Created from @doctest for `safe_var`
  # Source file: R/safe-arithmetic.R
  x <- 1:5
  expect_length(safe_var(x), 1)
})

